### ISSUE TITLE
No Code Issues But T-Pose only

### ISSUE THREAD

**Issue by Rizzlord** [pemguin005/Third-Person-Controller--SoulsLIke-Godot4#2]
Sorry i am new to godot, and i am trying to learn, when you start the template, the character only stands in t-pose. I figured i had to change "@export_node_path(Node3D) var PlayerCharacterMesh: NodePath" to "@export_node_path("Node3D") var PlayerCharacterMesh: NodePath" still not working, but code shows all is fine?

**Comment by catprisbrey** [comment]
Try reassigning the model animations to each action node inside the
animation player.

Sometimes they LOOK correct but Godot won't play them right, and by
choosing a different animation, and then reassigning the correct animation
again, it sorts it out and goes back to working correctly.

Again I haven't gotten to update this Godot 4 template since early betas,
and I'm too busy in the short term to dive into it and make sure it's bug
free.

**Comment by Rizzlord** [comment]
Okay, i had to change the "mode" for all animation transitions to auto but for the attacks i had to change it to "enable".
Thank you for your work, now i can test if i change from unreal to godot, because godot is very performant, even with Global illumination on! Although i have pc freezes from time to time in the editor, which is weird. rx 5700 xt

**Comment by catprisbrey** [comment]
Fixed by @KennethOshiro
